### DISCUSSION TITLE
Conncetion refused

### DISCUSSION THREAD

**Discussion by Welsyntoffie** [hollie/tailscale-caddy-proxy#9] [General]
Here is my compose file...

```
version: '3.6'

networks:
  tailscale_proxy_example:
    external: false

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    ports:
      - '8086:8086'
    volumes:
      - /mnt/media/influxdb:/var/lib/influxdb2


# Grafana - Graphical data visualization
  grafana:
    image: grafana/grafana-enterprise:10.4.2-ubuntu
    container_name: grafana
#   security_opt:
#     - no-new-privileges:false
    restart: unless-stopped
    depends_on:
      - influxdb
#      - ts-grafana
    networks:
     - tailscale_proxy_example
#    network_mode: container:ts-grafana
    ports:
      - "3001:3000"
    user: $PUID
    volumes:
      - /home/pieter/dockerdata/grafana:/var/lib/grafana

    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_INGRESS_USER: anonymous
#     GF_SECURITY_COOKIE_SAMESITE: none
#     GF_SECURITY_COOKIE_SECURE: "true"
      GF_SECURITY_LOGIN_REMEMBER_DAYS: "365"
      GF_DATE_FORMATS_INTERVAL_HOUR: DD/MM HH:mm
      GF_DATE_FORMATS_INTERVAL_DAY: DD/MM
#     GF_AUTH_BASIC_ENABLED: "true"

  tailscale-whoami-proxy:
    image: hollie/tailscale-caddy-proxy:latest
    volumes:
      - /home/pieter/dockerdata/grafana/tailscale:/var/lib/tailscale # Persist the tailscale state directory
    environment:
      - TS_HOSTNAME=Grafanahttps 	# Hostname you want this instance to have on the tailscale network
      - TS_TAILNET=Grafanahttps         # Your tailnet name without the .ts.net suffix!
      - TS_FUNNEL=on
      - CADDY_TARGET=grafana:3000	# Target service and port
#      - TS_EXTRA_ARGS=--accept-dns      # Optional extra arguments to pass when starting tailscale
#      - SKIP_CADDYFILE_GENERATION=1     # Set this if you want to be able to override /etc/caddy/Caddyfile via a volume mapping      
    restart: on-failure
    init: true
    networks:
     - tailscale_proxy_example
```

The funnel was not activating by the -TS arg. So I used the cli to activate funnel...
```
/ # tailscale funnel --bg 3000
Available on the internet:

https://grafanahttps.xxx.ts.net/
|-- proxy http://127.0.0.1:3000

Funnel started and running in the background.
To disable the proxy, run: tailscale funnel --https=443 off
/ # tailscale serve status

# Funnel on:
#     - https://grafanahttps.xxx.ts.net

https://grafanahttps.xxx.ts.net (Funnel on)
|-- / proxy http://127.0.0.1:3000
```

I did edit tailscale ACL file with tailscale ip and attr funnel. 
I did get a cert issued "Valid until 3 months from now"

When I acces it over https the tailscale log shows `http: proxy error: dial tcp 127.0.0.1:3000: connect: connection refused`
Futher down the logs... `handleIngress: got ingress conn for unconfigured "grafanahttps.xxx.ts.net:8443"; rejecting`
