### ISSUE TITLE
How to deal with apps that require two services

### ISSUE THREAD

**Issue by bruno-cobucci** [hollie/tailscale-caddy-proxy#14]
First of all, I love your software and I've been using it flawlessly for the last couple months.

However, when I was trying to install StoreDown [(as seem here)](https://github.com/FoxUSA/StoreDown/blob/master/docs/install.md) I ended up facing an issue. StoreDown requires couchdb database, which is declared as a separate service. When both the storedown service and the database service are declared in the same compose file, one runs at https and the other at http, meaning the connection to the database is not accepted. Then I tried running two separate compose files, with two separate taiscale-caddy-proxy services, one for each, and then connected all of them thought a network. But that didn't work either, now the connection is being refused.

So I think the real question is: how to deal with this type of situation, where an app requires an additional service, and they must talk to one another, and both of them must be https?

Thanks!

**Comment by hollie** [comment]
Hey Bruno,

thanks for the positive feedback ❤️ .

The nice thing of this docker image is that you are not obliged to force all services in HTTPS mode. Tailscale-caddy-proxy allows you to put the frontend behind the HTTPS proxy, all the rest of the containers can continue running in their default configuration.

I tried setting it up as a test for you, however, I don't get StoreDown running with persistent data over HTTP, I assume because there is something not working with the database connection. I did follow the setup instructions for the couched from the StoreDown wiki. I get the interface, I can add items but they are not retained in the database. 🤷‍♂️ 

Either way: once you have the HTTP version up and running the following should work:

```
networks:
  storedown:

volumes:
  tailscale-storedown-state:

services:
  storedown:
    image: foxusa/storedown
    restart: always
    ports:
      - "80:80"
    networks:
      - storedown

  couchdb:
    image: couchdb
    restart: always
    volumes:
      - ./data/data:/opt/couchdb/data #TODO set this to prevent accidentally deleting your database data
      - ./data/local.d:/opt/couchdb/etc/local.d # Prevents CORS setting from being removed
    ports:
      - "5984:5984"
    networks:
      - storedown
    environment:
      COUCHDB_USER: user #TODO set this
      COUCHDB_PASSWORD: password #TODO set this

  tailscale-storedown:
    image: hollie/tailscale-caddy-proxy:latest
    volumes:
      - tailscale-storedown-state:/var/lib/tailscale # Persist tailscale state
    environment:
      - TS_HOSTNAME=storedown # Hostname on the tailscale network
      - TS_TAILNET=<XXXXXXXX>       # Your tailnet name without the .ts.net suffix!
      - CADDY_TARGET=storedown:80        # Target service and port
    networks:
      - storedown
    restart: on-failure
    init: true
```

For the configuration of the database after adding the tailscale proxy, use the standard 'HTTP' protocol and as hostname 'couchdb' and port '5984'.

If this works you should even be able to remove the 'ports' sections from the first two services to ensure no ports are exposed to your local network, but only on the docker-compose specific 'storedown' network.

Please let me know if this works for you.

Regards,
 Lieven
