### ISSUE TITLE
Caddy not being issued certificates - can't connect

### ISSUE THREAD

**Issue by nigelsim** [hollie/tailscale-caddy-proxy#2]
I'm new to Caddy, so that is possibly where my problem lies.

I've setup a basic config, and it connects to Tailscale, but when I access the host over Tailscale I get

```
Accept: TCP{100.123.230.140:47326 > 100.106.38.155:80} 60 tcp ok
[unexpected] localbackend: got TCP conn w/o serveConfig; from 100.123.230.140:47326 to port 80
```

I've tried HTTP and HTTPS. The above is a HTTP attempt.

I've got HTTPS and MagicDNS enabled in Tailscale.

My docker compose is quite simple:
```
version: '2'

volumes:
  nextcloud:
  tailscale-proxy-state:

services:
  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html

  tailscale-proxy:
    image: hollie/tailscale-caddy-proxy:latest
    volumes:
      - tailscale-proxy-state:/var/lib/tailscale
    environment:
      - TS_HOSTNAME=nextcloud
      - TS_TAILNET=tailezxye
      - CADDY_TARGET=app:80

    restart: on-failure
    init: true
```

The Caddy startup messages suggest that maybe there is some missing config?

```
{"level":"info","ts":1697103625.3571339,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
{"level":"info","ts":1697103625.3657167,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//127.0.0.1:2019","//localhost:2019","//[::1]:2019"]}
{"level":"info","ts":1697103625.3663924,"logger":"http.auto_https","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":443}
{"level":"info","ts":1697103625.3668227,"logger":"http.auto_https","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
{"level":"info","ts":1697103625.3679645,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0004c2800"}
{"level":"info","ts":1697103625.3690476,"logger":"http","msg":"enabling HTTP/3 listener","addr":":443"}
{"level":"info","ts":1697103625.3693569,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/root/.local/share/caddy"}
{"level":"info","ts":1697103625.3698409,"msg":"failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details."}
{"level":"info","ts":1697103625.3709908,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
{"level":"info","ts":1697103625.3712015,"logger":"http.log","msg":"server running","name":"remaining_auto_https_redirects","protocols":["h1","h2","h3"]}
{"level":"info","ts":1697103625.3717875,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1697103625.3729112,"msg":"autosaved config (load with --resume flag)","file":"/root/.config/caddy/autosave.json"}
{"level":"info","ts":1697103625.372974,"msg":"serving initial configuration"}
```

The Caddyfile in the container is as follows, which I think is what is expected:

```
nextcloud.tailxyze.ts.net
reverse_proxy app:80
```
